### ISSUE TITLE
Modal interface does not work with translations

### ISSUE THREAD

**Issue by urbgimtam** [dimitrov-adrian/directus-extension-group-modal-interface#1]
Thank you for a great plugin.

Unfortunately, it doesn't seem to work / be compatible with the translation system

Neither if the modal is inside a translation collection or if a translation field is inside a modal.

**Comment by dimitrov-adrian** [comment]
@urbgimtam what do you mean. I tried to reproduce but it works fine. Can you give example scenario please?

Also which version of Directus?
